package com.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class TbRechargeRecord implements Serializable {
    /**
     * 主键
     */
    private Integer id;

    /**
     * 用户id
     */
    private Integer uid;

    /**
     * 操作人
     */
    private String name;

    /**
     * 充值金额
     */
    private Integer money;

    /**
     * 审核状态 0-审核中 1-审核通过
     */
    private Integer checkStatus;

    /**
     * 创建时间
     */
    private Date createDate;

    /**
     * 修改时间
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_recharge_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUid() {
        return uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getMoney() {
        return money;
    }

    public void setMoney(Integer money) {
        this.money = money;
    }

    public Integer getCheckStatus() {
        return checkStatus;
    }

    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Override
    public String toString() {
        return "TbRechargeRecord{" +
                "id=" + id +
                ", uid=" + uid +
                ", name='" + name + '\'' +
                ", money=" + money +
                ", checkStatus=" + checkStatus +
                ", createDate=" + createDate +
                ", updateDate=" + updateDate +
                '}';
    }
}